[env:rp2040-zero]
platform = raspberrypi
board = waveshare_rp2040_zero
framework = arduino
upload_protocol = picotool
;upload_port = /media/user/RPI-RP2/
upload_port = /dev/ttyACM0

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3